//! Wire-format pin vectors.
//!
//! The binary files under `tests/vectors/` were generated by the
//! `generate_vectors` test on the pre-restructure base (v2.0.0-rc.4,
//! `acd7f75`), before the core-extraction restructuring. Deployed systems
//! consume these exact bytes — the EVM adapter, for one, reads the 65-byte
//! delta proof (recovery byte stored Ethereum-style, +27) through
//! `ecrecover` — so the serialized form of every type here must never
//! change. The reading tests below must pass unmodified across any
//! refactoring of the in-memory types.

use anoma_rm_risc0::aggregation_instance::{
    ActionAggregated, AggregationInstance, ConsumedResourceAggregated, CreatedResourceAggregated,
};
use anoma_rm_risc0::delta_proof::{DeltaProof, DeltaWitness};
use anoma_rm_risc0::logic_instance::{AppData, ExpirableBlob};
use anoma_rm_risc0::transaction::{Aggregation, Delta, Transaction};
use anoma_rm_risc0::Digest;
use std::fs;
use std::path::PathBuf;

/// Delta message signed for the pinned proof. RFC6979 signing makes the
/// resulting signature deterministic, so the pinned proof is reproducible
/// from this message and the fixed witness scalar alone.
const DELTA_MESSAGE: &[u8] = b"arm wire vector delta message";

fn witness() -> DeltaWitness {
    DeltaWitness::from_bytes(&[0x11; 32]).expect("fixed scalar is in range")
}

fn proof() -> DeltaProof {
    anoma_rm_risc0::delta_proof::prove(DELTA_MESSAGE, &witness())
        .expect("deterministic proving succeeds")
}

fn rich_instance() -> AggregationInstance {
    let blob = |seed: u32| ExpirableBlob {
        blob: vec![seed, seed + 1, seed + 2],
        deletion_criterion: 1,
    };
    let app_data = |seed: u32| AppData {
        resource_payload: vec![blob(seed)],
        discovery_payload: vec![],
        external_payload: vec![blob(seed + 10)],
        application_payload: vec![blob(seed + 20)],
    };
    AggregationInstance {
        compliance_key: Digest::from_bytes([0xC0; 32]),
        kind_table_commitment: Digest::from_bytes([0xC1; 32]),
        actions: vec![
            ActionAggregated {
                consumed_publics: vec![ConsumedResourceAggregated {
                    resource_nullifier: Digest::from_bytes([0x01; 32]),
                    resource_logic_ref: Digest::from_bytes([0x02; 32]),
                    commitment_tree_root: Digest::from_bytes([0x03; 32]),
                    app_data: app_data(100),
                }],
                created_publics: vec![CreatedResourceAggregated {
                    resource_commitment: Digest::from_bytes([0x04; 32]),
                    resource_logic_ref: Digest::from_bytes([0x05; 32]),
                    app_data: app_data(200),
                }],
                delta_x: [0x11111111; 8],
                delta_y: [0x22222222; 8],
                action_tree_root: Digest::from_bytes([0x06; 32]),
            },
            ActionAggregated {
                consumed_publics: vec![],
                created_publics: vec![],
                delta_x: [0; 8],
                delta_y: [0; 8],
                action_tree_root: Digest::from_bytes([0x07; 32]),
            },
        ],
    }
}

fn aggregated_tx() -> Transaction {
    Transaction {
        actions: None,
        delta_proof: Delta::Proof(proof()),
        expected_balance: None,
        aggregation: Some(Aggregation {
            proof: vec![0xAB; 40],
            instance: rich_instance(),
        }),
    }
}

fn unaggregated_tx() -> Transaction {
    Transaction {
        actions: Some(vec![]),
        delta_proof: Delta::Witness(witness()),
        expected_balance: None,
        aggregation: None,
    }
}

fn vector_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors")
        .join(name)
}

fn read_vector(name: &str) -> Vec<u8> {
    fs::read(vector_path(name)).unwrap_or_else(|e| {
        panic!(
            "missing wire vector {name}: {e}. Vectors are committed; to regenerate \
             them ON THE PRE-RESTRUCTURE BASE run `cargo test --test wire_vectors \
             -- --ignored generate_vectors`."
        )
    })
}

/// Pin one type: the committed bytes must decode, the decoded value must
/// equal the reference construction, and re-encoding must reproduce the
/// committed bytes exactly.
macro_rules! pin {
    ($name:literal, $ty:ty, $reference:expr) => {{
        let bytes = read_vector($name);
        let decoded: $ty = bincode::deserialize(&bytes)
            .unwrap_or_else(|e| panic!("decode committed vector {}: {e}", $name));
        assert_eq!(decoded, $reference, "{}: decoded value drifted", $name);
        let reencoded = bincode::serialize(&decoded).expect("serialize");
        assert_eq!(reencoded, bytes, "{}: wire bytes drifted", $name);
    }};
}

#[test]
fn delta_proof_wire_pinned() {
    pin!("delta_proof.bin", DeltaProof, proof());
    // The last wire byte is the Ethereum-style recovery id (+27) that the
    // EVM adapter feeds to ecrecover.
    let bytes = read_vector("delta_proof.bin");
    let raw = &bytes[bytes.len() - 65..];
    assert!(
        raw[64] == 27 || raw[64] == 28,
        "recovery byte must be 27/28"
    );
}

#[test]
fn delta_witness_wire_pinned() {
    pin!("delta_witness.bin", DeltaWitness, witness());
    assert_eq!(witness().to_bytes(), [0x11; 32]);
}

#[test]
fn delta_enum_wire_pinned() {
    pin!("delta_enum_witness.bin", Delta, Delta::Witness(witness()));
    pin!("delta_enum_proof.bin", Delta, Delta::Proof(proof()));
}

#[test]
fn aggregation_instance_wire_pinned() {
    pin!(
        "aggregation_instance.bin",
        AggregationInstance,
        rich_instance()
    );
}

#[test]
fn transaction_wire_pinned() {
    pin!("transaction_aggregated.bin", Transaction, aggregated_tx());
    pin!(
        "transaction_unaggregated.bin",
        Transaction,
        unaggregated_tx()
    );
}

/// Generator, not a check: writes the vectors this module pins. Ignored so
/// it only runs by explicit request (`-- --ignored generate_vectors`), and
/// only ever on the pre-restructure base — regenerating on later code would
/// destroy the pin's meaning.
#[test]
#[ignore = "writes tests/vectors/*; run once on the pre-restructure base only"]
fn generate_vectors() {
    fs::create_dir_all(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/vectors"))
        .expect("create vectors dir");
    let write = |name: &str, bytes: Vec<u8>| {
        fs::write(vector_path(name), bytes).unwrap_or_else(|e| panic!("write {name}: {e}"));
    };
    write("delta_proof.bin", bincode::serialize(&proof()).unwrap());
    write("delta_witness.bin", bincode::serialize(&witness()).unwrap());
    write(
        "delta_enum_witness.bin",
        bincode::serialize(&Delta::Witness(witness())).unwrap(),
    );
    write(
        "delta_enum_proof.bin",
        bincode::serialize(&Delta::Proof(proof())).unwrap(),
    );
    write(
        "aggregation_instance.bin",
        bincode::serialize(&rich_instance()).unwrap(),
    );
    write(
        "transaction_aggregated.bin",
        bincode::serialize(&aggregated_tx()).unwrap(),
    );
    write(
        "transaction_unaggregated.bin",
        bincode::serialize(&unaggregated_tx()).unwrap(),
    );
}
