[package]
name = "simple-transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-transfer-methods = { path = "methods" }
risc0-zkvm = "3.0.3"
arm = { path = "../../arm", default-features = false }
