[package]
name = "simple-transfer-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "3.0.3", features = ["unstable"] }

[package.metadata.risc0]
methods = ["guest"]
