"""Execute the link-check cases on deployed link-check programs.

Usage: exec_check.py RPC_URL FEE_PAYER PROGRAM_ID [PROGRAM_ID ...]

Each line of exec_cases.txt (generated by anoma-rm-solana's
`link_check_exec_cases_are_current` test) is `name expected data-hex`, where
`expected` is `ok` or the custom program error the program returns. Every
case is simulated against every program, with signature verification off
and the RPC's recent blockhash, so the fee payer only has to exist. Exits 1
if any outcome differs from the expected one.
"""

import base64
import json
import pathlib
import sys
import time
import urllib.request

ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58decode(text):
    number = 0
    for char in text:
        number = number * 58 + ALPHABET.index(char)
    body = number.to_bytes((number.bit_length() + 7) // 8, "big")
    raw = b"\0" * (len(text) - len(text.lstrip("1"))) + body
    if len(raw) != 32:
        raise ValueError(f"{text} is not a 32-byte key")
    return raw


def compact_u16(value):
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return bytes(out)


def transaction(fee_payer, program_id, data):
    """A legacy transaction: one zero signature, one instruction with no accounts."""
    message = (
        bytes([1, 0, 1])  # one signer (the fee payer); the program is read-only
        + compact_u16(2)
        + fee_payer
        + program_id
        + bytes(32)  # blockhash, replaced by the RPC
        + compact_u16(1)
        + bytes([1])  # program id index
        + compact_u16(0)
        + compact_u16(len(data))
        + data
    )
    return compact_u16(1) + bytes(64) + message


def rpc(rpc_url, method, params):
    request = {"jsonrpc": "2.0", "id": 1, "method": method, "params": params}
    post = urllib.request.Request(
        rpc_url, json.dumps(request).encode(), {"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(post) as response:
        body = json.load(response)
    if "error" in body:
        raise RuntimeError(f"{method} failed: {body['error']}")
    return body["result"]


def wait_until_executable(rpc_url):
    """The loader makes a program executable from the slot after its
    deployment. The deployments landed at or before the current processed
    slot, so wait for the confirmed slot to pass it (60 seconds at most)."""
    deployed_by = rpc(rpc_url, "getSlot", [{"commitment": "processed"}])
    deadline = time.monotonic() + 60
    while rpc(rpc_url, "getSlot", [{"commitment": "confirmed"}]) <= deployed_by:
        if time.monotonic() > deadline:
            sys.exit(f"the confirmed slot did not pass slot {deployed_by} within 60 seconds")
        time.sleep(0.1)


def simulate(rpc_url, tx):
    # `confirmed`: the default, `finalized`, does not see a program deployed
    # moments ago.
    config = {
        "encoding": "base64",
        "sigVerify": False,
        "replaceRecentBlockhash": True,
        "commitment": "confirmed",
    }
    return rpc(rpc_url, "simulateTransaction", [base64.b64encode(tx).decode(), config])["value"]


def outcome(value):
    error = value["err"]
    if error is None:
        return "ok"
    instruction_error = error.get("InstructionError") if isinstance(error, dict) else None
    if instruction_error and isinstance(instruction_error[1], dict) and "Custom" in instruction_error[1]:
        return str(instruction_error[1]["Custom"])
    return json.dumps(error)


def main():
    rpc_url, fee_payer, *program_ids = sys.argv[1:]
    if not program_ids:
        sys.exit(__doc__)
    cases = [
        line.split(" ")
        for line in (pathlib.Path(__file__).parent / "exec_cases.txt").read_text().splitlines()
    ]
    if not cases:
        sys.exit("exec_cases.txt has no cases")
    wait_until_executable(rpc_url)
    failures = 0
    for program_id in program_ids:
        for name, expected, data_hex in cases:
            value = simulate(
                rpc_url, transaction(b58decode(fee_payer), b58decode(program_id), bytes.fromhex(data_hex))
            )
            got = outcome(value)
            status = "ok" if got == expected else "MISMATCH"
            print(f"{program_id} {name}: expected {expected}, got {got}, {value['unitsConsumed']} CU [{status}]")
            if got != expected:
                failures += 1
                print("\n".join(value.get("logs") or []), file=sys.stderr)
    if failures:
        sys.exit(f"{failures} case(s) did not execute as expected")


main()
