[package]
name = "anoma-rm-solana"
description = "Solana on-chain verification for the Anoma Resource Machine"
version = "2.0.0-rc.4"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anoma-rm-risc0 = { path = "../arm", default-features = false, features = [
  "borsh",
] }
solana-program = "2.1"
solana-secp256k1 = "0.2.1"
thiserror = "2.0.6"

[dev-dependencies]
k256 = { version = "=0.13.3", features = ["arithmetic", "ecdsa", "std"] }
