[package]
name = "counter-app"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
counter-witness = { path = "../counter_witness" }
arm= { path = "../../../arm" }
rand = "0.8"
risc0-zkvm = "=2.1.0"
lazy_static = "1.5.0"
hex = "0.4"
