[package]
name = "variable-depth-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "2.1.0", features = ["std", "unstable"] }
arm = { path = "../../../../arm", features = ["logic_circuit"], default-features = false }
