[workspace]
resolver = "2"
members = [ "compliance_circuit", "trivial_logic", "aggregation_circuits"]

 # Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true