[package]
name = "counter-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "2.1.0", default-features = false, features = ['std'] }
counter-witness = { path = "../../../../examples/simple_counter_application/counter_witness" }
