[package]
name = "batch-aggregation-guest"
version = "1.0.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3", features = [
  "std",
  "unstable",
], default-features = false }
anoma-rm-risc0 = { path = "../../../../arm", features = [
  "aggregation_circuit",
], default-features = false }
borsh = { version = "1.5", default-features = false, features = [
  "derive",
], optional = true }
alloy-sol-types = { version = "1", default-features = false, optional = true }

[features]
borsh = ["dep:borsh"]
evm = ["dep:alloy-sol-types"]
