[package]
name = "logic-test"
version = "1.0.0"
edition = "2021"

[dependencies]
logic-test-methods = { path = "methods" }
risc0-zkvm = "3.0.3"
anoma-rm-risc0 = { version = "1.1.0", default-features = false }
anoma-rm-risc0-test-witness = { version = "1.1.0" }

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
prove = ["risc0-zkvm/prove"]
bonsai = ["risc0-zkvm/bonsai"]
