// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.

fn main() {
    // Do we need some separate circuit tests here? Seems duplicate with tests
    // in the counter application
}
