[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
counter-methods = { path = "../counter_logic_circuit" }
serde = "1.0"
counter = { path = "../counter" }
arm= { path = "../../../arm" }
rand = "0.8"
