[package]
name = "sequential_aggregation"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "2.1.0", features = ["std", "unstable"], default-features = false }
arm = { path = "../../../../../arm", features = ["aggregation_circuit"], default-features = false}