[workspace]
resolver = "2"
members = ["counter", "counter_logic_circuit", "app"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
