[package]
name = "kudo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
aarm_core = { path = "../../../aarm_core" }
serde = { version = "1.0.197", default-features = false }
risc0-zkvm = "2.1.0"
rand = "0.8"
